# Generated by Django 4.1.6 on 2023-06-12 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoaiSanPham',
            fields=[
                ('ma_loai', models.IntegerField(primary_key=True, serialize=False)),
                ('ten_loai', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'loai_san_pham',
            },
        ),
        migrations.CreateModel(
            name='NhomSanPham',
            fields=[
                ('ma_nhom', models.IntegerField(primary_key=True, serialize=False)),
                ('ten_nhom', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'nhom_san_pham',
            },
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('ma_san_pham', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('ten_san_pham', models.CharField(max_length=300, null=True)),
                ('ten_tieu_de', models.CharField(max_length=100, null=True)),
                ('hinh_anh', models.TextField(null=True)),
                ('cong_dung', models.TextField()),
                ('doi_tuong', models.CharField(max_length=100, null=True)),
                ('dang_bao_che', models.CharField(max_length=100, null=True)),
                ('id_loai', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.loaisanpham')),
            ],
            options={
                'db_table': 'san_pham',
            },
        ),
        migrations.AddField(
            model_name='loaisanpham',
            name='nhom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.nhomsanpham'),
        ),
    ]
